language: node_js

git:
  depth: 1

node_js:
  - 'node'
  - '14'
  - '12'
  - '10'

install:
  - npm install

script:
  - npm test
  - npm run clean
  - npm start

cache:
  directories:
    - 'node_modules'
